# (C) Ardendo SE 2008
#
# Released under the LGPL

Import(['local_env'])

local_env.packages( 'boost', 'boost_date_time', 'boost_system' )
options = local_env.optional( 'rubberband' )
build = options[ 'have_rubberband' ]

if build:
	object = local_env.plugin( 'openmedialib_rubberband', [ 'plugin_rubberband.cpp' ] )
	local_env.copy_project_files( local_env[ 'stage_ml_plugin' ], object + [ 'plugin_rubberband.opl' ] )
	Return( 'object' )
