# (C) Ardendo SE 2008
#
# Released under the LGPL

Import(['local_env'])

local_env.packages( 'boost', 'boost_thread', 'boost_date_time', 'boost_system', 'loki', )
options = local_env.optional( 'rubberband' )
build = options[ 'have_rubberband' ]

if build:
	src = [ 'plugin_rubberband.cpp' ]
	
	if local_env[ 'PLATFORM' ] == 'win32' :
		src.append( 'msw/rubberbandplugin.rc' )
	
	object = local_env.plugin( 'openmedialib_rubberband', src )
	local_env.copy_project_files( local_env[ 'stage_ml_plugin' ], object + [ 'plugin_rubberband.opl' ] )
	Return( 'object' )
