# (C) Ardendo SE 2008
#
# Released under the LGPL

Import(['local_env'])

local_env.packages( 'boost_thread' )

object = local_env.plugin( 'openmedialib_template', [ 'template_plugin.cpp' ] )

local_env.Install( local_env[ 'stage_ml_plugin' ], [ object, 'template_plugin.opl' ] )

Return( 'object' )
