# (C) Ardendo SE 2008
#
# Released under the LGPL

Import(['local_env'])

local_env.packages( 'boost_thread' )

local_env[ 'win_target_path' ] = '$stage_ml_plugin' 

object = local_env.plugin( 'openmedialib_template', [ 'template_plugin.cpp' ] )

local_env.copy_project_files( local_env[ 'stage_ml_plugin' ], object + [ 'template_plugin.opl' ] )

Return( 'object' )
