# (C) Ardendo SE 2008
#
# Released under the LGPL

Import(['local_env'])

options = local_env.optional( 'openal' )

if options[ 'have_openal' ]:
	local_env.packages( 'boost_thread', 'openal' )
	local_env[ 'win_target_path' ] = '$stage_ml_plugin'
	object = local_env.plugin( 'openmedialib_openal', [ 'openal_plugin.cpp' ] )
	local_env.copy_project_files( local_env[ 'stage_ml_plugin' ], object + [ 'openal_plugin.opl' ] )
