Import(['local_env'])

local_env.packages( 'boost_thread' )

object = local_env.SharedLibrary( 'openmedialib_gensys', [ 'gensys_plugin.cpp' ] )

local_env.Install( local_env[ 'stage_ml_plugin' ], [ object, 'gensys_plugin.opl' ] )

Return( 'object' )
