Import(['local_env'])

local_env.packages( 'boost_thread', 'boost_filesystem', 'openmedialib' )

object = local_env.shared_library( 'openmedialib_ml', [ 'filter.cpp', 'frame.cpp', 'ml.cpp', 'openmedialib_plugin.cpp', 'utilities.cpp' ] )

local_env.Install( local_env[ 'stage_libdir' ], object )
local_env.Install( local_env[ 'ml_include' ], [ 'audio.hpp', 'config.hpp', 'filter.hpp', 'frame.hpp', 'input.hpp', 'ml.hpp', 'openmedialib_plugin.hpp', 'store.hpp', 'utilities.hpp' ] )

Return( 'object' )
