# (C) Ardendo SE 2008
#
# Released under the LGPL

Import(['local_env'])

local_env.packages( 'boost_thread', 'boost_filesystem', 'boost_system', 'build_ml', 'boost_date_time', 'libavformat', 'loki' )

src = [ 'analyse_mpeg2.cpp',
		'audio_channel_convert.cpp',
        'audio_sample_calcs.cpp',
        'audio_utilities.cpp',
        'awi.cpp',
        'filter.cpp',
        'frame.cpp',
        'indexer.cpp',
        'ml.cpp',
        'openmedialib_plugin.cpp',
        'scope_handler.cpp',
        'utilities.cpp' ]

if local_env[ 'PLATFORM' ] == 'win32':
	src.append( 'msw/medialib.rc' )

object = local_env.shared_library( 'openmedialib_ml', src )

local_env.release( object )

local_env.copy_files( local_env[ 'stage_profiles' ], Dir('#').abspath + '/profiles', perms = 0755 )

if local_env[ 'PLATFORM' ] != 'win32' :
	local_env.copy_project_files( local_env[ 'ml_include' ], 
		[ 	'analyse_mpeg2.hpp',
			'audio.hpp', 
			'audio_cast.hpp', 
			'audio_channel_convert.hpp', 
			'audio_channel_extract.hpp', 
			'audio_convert.hpp', 
			'audio_interface.hpp', 
			'audio_mix_matrix.hpp', 
			'audio_place.hpp', 
			'audio_template.hpp', 
			'audio_types.hpp', 
			'audio_utilities.hpp', 
			'audio_volume.hpp', 
			'awi.hpp', 
			'config.hpp', 
			'filter.hpp', 
			'filter_encode.hpp', 
			'filter_simple.hpp', 
			'frame.hpp', 
			'input_creator_handler.hpp', 
			'input.hpp', 
			'indexer.hpp', 
			'ml.hpp', 
			'openmedialib_plugin.hpp', 
			'packet.hpp', 
			'scope_handler.hpp', 
			'stack.hpp',
			'store.hpp', 
			'types.hpp', 
			'utilities.hpp' ] )

Return( 'object' )
