# (C) Ardendo SE 2008
#
# Released under the LGPL

Import(['local_env'])

local_env.packages( 'boost' )
options = local_env.optional( 'sox' )
build = options[ 'have_sox' ]

if build:
	
	src = [ 'plugin_sox.cpp' ]

	if local_env[ 'PLATFORM' ] == 'win32' :
		src.append( 'msw/soxplugin.rc' )
		
	object = local_env.plugin( 'openmedialib_sox', src )
	local_env.copy_project_files( local_env[ 'stage_ml_plugin' ], object + [ 'plugin_sox.opl' ] )
	Return( 'object' )
