# (C) Ardendo SE 2008
#
# Released under the LGPL

Import(['local_env'])

options = local_env.optional( 'sox' )
build = options[ 'have_sox' ]

if build:
	object = local_env.plugin( 'openmedialib_sox', [ 'plugin_sox.cpp' ] )
	local_env.copy_project_files( local_env[ 'stage_ml_plugin' ], object + [ 'plugin_sox.opl' ] )
	Return( 'object' )
