# (C) Ardendo SE 2008
#
# Released under the LGPL

import sys

Import(['local_env'])

local_env.packages( 'boost_thread', 'boost_filesystem', 'boost_regex', 'boost_python' )

prefix = sys.exec_prefix
if local_env[ 'target' ] == 'vs2003' or local_env[ 'target' ] == 'vs2008':
	local_env.Append( CPPPATH = [ '%s/include' % prefix ] )
else:
	version = sys.version_info
	local_env.Append( CPPPATH = [ '%s/include/python%d.%d' % ( prefix, version[ 0 ], version[ 1 ] ) ] )

local_env[ 'SHLIBPREFIX' ] = ''

object = local_env.shared_library( 'openpluginlib' + [ '', '_d' ][ int( local_env.debug ) ], [ 
	'py.cpp', 
	'openpluginlib.cpp', 
	'string.cpp', 
	'pcos/key.cpp', 
	'pcos/observer.cpp', 
	'pcos/subject.cpp', 
	'pcos/property.cpp', 
	'pcos/any.cpp', 
	'pcos/property_container.cpp', 
	'pcos/visitor.cpp' ] )

local_env.Install( local_env[ 'python_packages' ], object )

Return( 'object' )
