# (C) Ardendo SE 2008
#
# Released under the LGPL

import sys

Import(['local_env'])

local_env.packages( 'boost_thread', 'boost_filesystem', 'boost_regex', 'boost_python' )

prefix = sys.exec_prefix
if local_env[ 'target' ] == 'vs2003' or local_env[ 'target' ] == 'vs2008':
	local_env.Append( CPPPATH = [ '%s/include' % prefix ] )
	local_env.Append( LIBPATH = [ '%s/lib' % prefix ] )
else:
	version = sys.version_info
	local_env.Append( CPPPATH = [ '%s/include/python%d.%d' % ( prefix, version[ 0 ], version[ 1 ] ) ] )

local_env[ 'SHLIBPREFIX' ] = ''

object = local_env.shared_library( 'openimagelib' + [ '', '_d' ][ int( local_env.debug ) ], [ 'il.cpp', 'py.cpp' ] )

local_env.Install( local_env[ 'python_packages' ], object )

Return( 'object' )
