# (C) Ardendo SE 2008
#
# Released under the LGPL

Import(['local_env'])

options = local_env.optional( 'sdl' )

if options[ 'have_sdl' ]:
	local_env.packages( 'boost_thread', 'boost_system', 'boost_date_time' )

	local_env[ 'win_target_path' ] = '$stage_ml_plugin'

	src = [ 'sdl_plugin.cpp' ]

	if local_env[ 'PLATFORM' ] == 'win32' :
		src.append( 'msw/sdlplugin.rc' )

	object = local_env.plugin( 'openmedialib_sdl', src )

	local_env.copy_project_files( local_env[ 'stage_ml_plugin' ], object + [ 'sdl_plugin.opl' ] )

	Return( 'object' )
else:
	print "WARNING: SDL library not found - disabling plugin"
