# (C) Ardendo SE 2008
#
# Released under the LGPL

Import(['local_env'])

local_env.packages( 'boost_thread', 'boost_filesystem', 'boost_system', 'boost_regex', 'boost_date_time', 'build_pl', 'xerces' )

local_env.Append( CPPDEFINES = [ 'OPENIMAGELIB_PLUGINS=\\\"%s\\\"' % local_env[ 'install_il_plugin' ] ] )
local_env.Append( CPPDEFINES = [ 'OPENMEDIALIB_PLUGINS=\\\"%s\\\"' % local_env[ 'install_ml_plugin' ] ] )

libxml2_sources = [ ]
msxml_sources = [ ]

if local_env[ 'PLATFORM' ] == 'darwin' :
	local_env.Append( FRAMEWORKS  = 'CoreServices' )

extras = { 'posix' : libxml2_sources, 'darwin' : libxml2_sources, 'win32' : msxml_sources }

object = local_env.shared_library( 'openpluginlib_pl', [ 	
	'bind_info.cpp',
	'fast_math.cpp',
	'log.cpp',
	'openplugin.cpp',
	'openpluginlib.cpp',
	'opl_importer.cpp',
	'registry.cpp',
	'utf8_utils.cpp',
	'opl_parser_action.cpp',
	'pool.cpp',
	'timer.cpp',
	'pcos/key.cpp',
	'pcos/property.cpp',
	'pcos/property_container.cpp',
	'pcos/subject.cpp'
] + extras[ local_env[ 'PLATFORM' ] ] )

local_env.release( object )

if local_env[ 'PLATFORM' ] != 'win32' :
	local_env.copy_project_files( local_env[ 'pl_include' ], [ 
		'bind_info.hpp',
		'discovery_traits.hpp', 
		'openplugin.hpp', 
		'openpluginlib.hpp', 
		'config.hpp', 
		'log.hpp', 
		'pool.hpp', 
		'utf8_utils.hpp', 
		'string.hpp', 
		'timer.hpp', 
		'geometry.hpp', 
		'string.hpp', 
	] )

if local_env[ 'PLATFORM' ] != 'win32' :
	local_env.copy_project_files( local_env[ 'pcos_include' ], [ 
		'pcos/key.hpp', 
		'pcos/observer.hpp', 
		'pcos/iproperty_container.hpp', 
		'pcos/property.hpp', 
		'pcos/property_container.hpp', 
		'pcos/subject.hpp', 
		'pcos/any.hpp', 
		'pcos/visitor.hpp', 
		'pcos/isubject.hpp', 
		'pcos/iclonable.hpp'
	] )

Return( 'object' )
