import os

Import(['local_env'])

local_env.packages( 'boost_unit_test_framework', 'boost_regex', 'boost_filesystem', 'boost_date_time', 'boost_thread', 'boost_system', 'xerces', 'libavformat' )
local_env.optional( 'ffmpeg' )
options = local_env.optional( 'x264', 'ffmpeg_x264_adapter' )

test_sources = [
	'src/main.cpp',
	'src/utils.cpp',
	'src/io_tester.cpp',
	'src/test_awi.cpp',
	'src/test_custom_io.cpp',
	'src/test_avformat_plugin.cpp',
	'src/test_wav.cpp',
	'src/test_wav_input.cpp',
	'src/test_wav_store.cpp',
	'src/test_compositor_filter.cpp',
	'src/test_frame_list_filter.cpp',
	'src/test_utilities.cpp',
	'src/test_lock_filter.cpp',
	'src/test_filter_store.cpp',
	'src/test_decode_plugin.cpp',
	'src/test_aml_stack_input.cpp',
	]

if options[ 'have_x264' ] and options[ 'have_ffmpeg_x264_adapter' ]:
	test_sources.append( 'src/test_x264_encoding.cpp' )

object = local_env.console_program( 'openmedialib_unit_tests', test_sources )
local_env.release( object )

mock = local_env.plugin( 'openmedialib_mock', 'mocks/plugin_mock.cpp' )
local_env.copy_project_files( local_env[ 'stage_ml_plugin' ], mock + [ 'mocks/plugin_mock.opl' ] )
local_env.copy_project_files( os.path.join( local_env[ 'ml_include' ], 'unittest', 'mocks'),
	['mocks/mock_filter.hpp', 'mocks/mock_frame.hpp', 'mocks/mock_input.hpp', 'mocks/mock_store.hpp'])

Return( 'object' )
