Import(['local_env'])

local_env.packages( 'boost_unit_test_framework', 'boost_regex', 'boost_filesystem', 'boost_date_time', 'boost_thread', 'boost_system', 'xerces', 'libavformat' )
local_env.optional( 'ffmpeg' )

test_sources = [
	'src/main.cpp',
	'src/io_tester.cpp',
	'src/test_awi.cpp',
	'src/test_custom_io.cpp',
	'src/test_avformat_plugin.cpp',
	'src/test_wav_store.cpp',
	'src/test_compositor_filter.cpp',
	'src/test_frame_list_filter.cpp',
	'src/test_utilities.cpp',
	]

object = local_env.console_program( 'openmedialib_unit_tests', test_sources )
local_env.release( object )

Return( 'object' )
