# (C) Ardendo SE 2008
#
# Released under the LGPL

Import(['local_env'])

local_env.packages( 'boost_thread', 'libavformat', 'boost_date_time', 'boost_system', 'boost_filesystem', 'loki' )
local_env.optional( 'ffmpeg', 'libavformat', 'libavcodec', 'libavutil', 'libavcore' )
options = local_env.optional( 'libswscale' )

if options[ 'have_libswscale' ]:
    local_env.Append( CPPDEFINES = [ 'HAVE_SWSCALE' ] )

if local_env[ 'PLATFORM' ] == 'win32' :
	local_env.Append( CPPDEFINES = [ '_SCL_SECURE_NO_WARNINGS', '_CRT_SECURE_NO_WARNINGS' ] )

object = local_env.plugin( 'openmedialib_avformat', [ 'avformat_plugin.cpp', 'filter_avdecode.cpp', 'filter_resampler.cpp', 'input_avformat.cpp', 'store_avformat.cpp' ] )

local_env.copy_project_files( local_env[ 'stage_ml_plugin' ], object + [ 'avformat_plugin.opl' ] )

Return( 'object' )
