# (C) Ardendo SE 2008
#
# Released under the LGPL

Import(['local_env'])

local_env.packages( 'boost_thread', 'libavformat', 'boost_date_time' )
local_env.optional( 'libswscale' )

object = local_env.plugin( 'openmedialib_avformat', [ 'avformat_plugin.cpp' ] )

local_env.copy_project_files( local_env[ 'stage_ml_plugin' ], object + [ 'avformat_plugin.opl' ] )

Return( 'object' )
