Import(['main_env'])

local_env = main_env.Clone( )
local_env.UseBoost( 'boost_thread', 'boost_filesystem' )
local_env.InstallName( 'libopenimagelib_il' )

object = local_env.SharedLibrary( 'openimagelib_il', [ 'il.cpp', 'openimagelib_plugin.cpp', 'utility.cpp' ] )

local_env.Install( local_env.stage_libdir( ), object )
local_env.Install( local_env.stage_include( ) + '/ardome-ml/openimagelib/il', [ 'basic_image.hpp', 'compression_traits.hpp', 'config.hpp', 'float_traits.hpp', 'il.hpp', 'noise_traits.hpp', 'openimagelib_plugin.hpp', 'rgb_traits.hpp', 'traits.hpp', 'utility.hpp', 'yuv_traits.hpp' ] )

