# (C) Ardendo SE 2008
#
# Released under the LGPL

Import(['local_env'])

local_env.packages( 'boost_thread', 'boost_system', 'boost_filesystem', 'build_il', 'boost_date_time' )

object = local_env.shared_library( 'openimagelib_il', [ 'il.cpp', 'openimagelib_plugin.cpp', 'utility.cpp' ] )

local_env.release( object )

local_env.copy_project_files( local_env[ 'il_include' ], [ 
	'basic_image.hpp', 
	'compression_traits.hpp', 
	'config.hpp', 
	'float_traits.hpp', 
	'il.hpp', 'noise_traits.hpp', 
	'openimagelib_plugin.hpp', 
	'rgb_traits.hpp', 
	'traits.hpp', 
	'utility.hpp', 
	'yuv_traits.hpp' ] )

Return( 'object' )
