#!/usr/bin/env python

import aml
import sys
import signal

def stop_server( signl, frme ):
	global player
	player.control_end( )
	return 0

signal.signal( signal.SIGINT, stop_server )

aml.init( )

player = aml.thread_player( )
player.create( sys.argv[ 1: ] )

player.control_start( )

server = aml.server( player, http_port = 55379 )
server.start( )

try:
	player.run( )
except KeyboardInterrupt:
	sys.exit( 0 )
finally:
	player.control_end( )

