#!/usr/bin/env python

import amly
import sys

server = 'localhost'
port = 55378

if len( sys.argv ) > 1:
	server = sys.argv[ 1 ]

if len( sys.argv ) > 2:
	port = int( sys.argv[ 2 ] )

amly.tkplay.run( server, port )

