#!/usr/bin/env python

import amlx
import sys

server = 'localhost'
port = 55378

if len( sys.argv ) > 1:
	server = sys.argv[ 1 ]

if len( sys.argv ) > 2:
	port = int( sys.argv[ 2 ] )

amlx.transport.run( server, port )

