#!/usr/bin/env python

import sys
import struct

if sys.argv[ 1 ] != '-':
	file = open( sys.argv[ 1 ], 'rb' )
else:
	file = sys.stdin

try:
	data = file.read( 8 )
	if len( data ) == 8:
		id = data[ 0 : 3 ]
		ver = data[ 3 : 4 ]
		( created, ) = struct.unpack( '!l', data[ 4 : ] )
	else:
		raise( Exception( 'File too short' ) )

	if id == 'AWI' and ver == '2':
		print id, ver, created
	else:
		raise( Exception( 'Unsupported index type' ) )

	while True:
		data = file.read( 20 )
		if len( data ) == 20:
			( reserved, ) = struct.unpack( '!h', data[ 0 : 2 ] )
			if reserved != 0: break
			( frames, frame, offset, length ) = struct.unpack( '!hlql', data[ 2 : ] )
			print frame, frames, offset, length
		else:
			break

except Exception, e:
	pass

