#!/usr/bin/env python

import sys
import struct
from datetime import datetime

if sys.argv[ 1 ] != '-':
	file = open( sys.argv[ 1 ], 'rb' )
else:
	file = sys.stdin

try:
	data = file.read( 8 )
	if len( data ) == 8:
		id = data[ 0 : 3 ]
		ver = data[ 3 : 4 ]
		( created, ) = struct.unpack( '!l', data[ 4 : ] )
	else:
		raise( Exception( 'File too short' ) )

	if id == 'AWI' and ver == '2':
		print id, ver, created
	elif id == 'AWI' and ver == '3':
		# Read past the header for now
		file.read( 56 )
	else:
		raise( Exception( 'Unsupported index type' ) )

	while True:
		data = file.read( 20 )
		if len( data ) == 20:
			( footercheck, ) = struct.unpack( '!Q', data[ 0 : 8 ] )
			if footercheck == 0xffffffffffffffff:
				print '\n-= AWI footer =-'
				( creationtimestamp, ) = struct.unpack( '!L', data[ 8 : 12 ] )
				creationdatetime = datetime.fromtimestamp( creationtimestamp )
				print "File was closed on: ", creationdatetime
				( maxframe, ) = struct.unpack( '!h', data[ 12 : 14 ] )
				print 'Longest GOP in file:', maxframe
				break
			else:
				( reserved, ) = struct.unpack( '!h', data[ 0 : 2 ] )
				if ver == '2' and reserved != 0: break
				( frames, frame, offset, length ) = struct.unpack( '!hlql', data[ 2 : ] )
				print frame, frames, offset, length
		else:
			break

except Exception, e:
	pass

