Import(['local_env'])
import os

if local_env['target'] == 'linux32':
	options = local_env.packages( 'gdk-pixbuf-2.0', 'librsvg-2.0', 'gthread-2.0', 'libswscale', 'boost_thread' )

	local_env.Append( CPPDEFINES = [ 'HAVE_LIBRSVG' ] )

	srcs = [ 'rsvg_plugin.cpp',
		'filter_title.cpp',
		'input_librsvg.cpp',  
		'filter_librsvg.cpp', ]

	bin = local_env.plugin( 'openmedialib_rsvg', srcs )

	local_env.copy_project_files( local_env[ 'stage_ml_plugin' ], bin + [ 'aml_rsvg.opl' ])

	Return( 'bin' )

