# (C) Ardendo SE 2008
#
# Released under the LGPL

Import(['local_env'])

local_env.packages( 'boost_filesystem' , 'loki')

object = local_env.plugin( 'plugin_test_assembly', [ 'plugin_assembly.cpp' ], pre = [ 'precompiled_headers.cpp', 'precompiled_headers.hpp' ] )

local_env.copy_project_files( local_env[ 'stage_mf_plugin' ], object + [ 'plugin_test_assembly.xml' ] )

Return( 'object' )
