# (C) Ardendo SE 2008
#
# Released under the LGPL

Import(['local_env'])

options = local_env.optional( 'caca' )
build = options[ 'have_caca' ]

if build:
	local_env[ 'win_target_path' ] = '$stage_ml_plugin'

	object = local_env.plugin( 'openmedialib_caca', [ 'caca_plugin.cpp' ] )

	local_env.copy_project_files( local_env[ 'stage_ml_plugin' ], object + [ 'caca_plugin.opl' ] )

	Return( 'object' )
