Import(['local_env'])
import os

local_env.packages( 'boost_regex', 'boost_thread', 'boost_date_time', 'boost_filesystem', 'boost_system', 'cairo')

srcs = [ 'textoverlay_plugin.cpp', 'filter_textoverlay.cpp' ]

if local_env[ 'PLATFORM' ] == 'win32':
	local_env.Append( CPPDEFINES = ['_CRT_SECURE_NO_WARNINGS'] )

# Make sure we place the binary correctly on windows
local_env[ 'win_target_path' ] = '$stage_ml_plugin'

bin = local_env.plugin( 'openmedialib_textoverlay', srcs )

local_env.copy_project_files( local_env[ 'stage_ml_plugin' ], bin + [ 'aml_textoverlay.opl' ])

Return( 'bin' )

